env:
  es6: true
  browser: true
  node: true
  jest: true
  es2021: true

extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - airbnb
  - airbnb-typescript

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: "./tsconfig.json"

plugins:
  - react
  - '@typescript-eslint'
  - eslint-plugin-prettier
  - eslint-plugin-react-hooks

settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx

  react:
    version: detect

rules:
  import/extensions: 0
  react/jsx-filename-extension: [2, 
    { 'extensions': ['.js', '.jsx', '.ts', '.tsx'] }
  ]
  react/function-component-definition: 0
  import/prefer-default-export: 0